# NvBot3 - Configuración Anti-Overfitting y 30 Monedas Estratégicas

# =============================================================================
# SELECCIÓN ESTRATÉGICA DE 30 MONEDAS
# =============================================================================
data:
  # 30 monedas organizadas por tiers estratégicos
  symbols:
    # Tier 1: Blue Chips (10 monedas) - Base estable del portfolio
    tier_1: ['BTCUSDT', 'ETHUSDT', 'BNBUSDT', 'ADAUSDT', 'SOLUSDT', 
             'XRPUSDT', 'DOTUSDT', 'LINKUSDT', 'MATICUSDT', 'AVAXUSDT']
    
    # Tier 2: Strong Alts (10 monedas) - DeFi y protocolos establecidos
    tier_2: ['UNIUSDT', 'AAVEUSDT', 'MKRUSDT', 'SUSHIUSDT', 'COMPUSDT',
             'YFIUSDT', 'SNXUSDT', 'CRVUSDT', '1INCHUSDT', 'ALPHAUSDT']
    
    # Tier 3: Emerging Sectors (10 monedas) - Diversificación sectorial
    tier_3: ['SANDUSDT', 'MANAUSDT', 'ENJUSDT', 'CHZUSDT', 'BATUSDT',
             'ZRXUSDT', 'STORJUSDT', 'OCEANUSDT', 'FETUSDT', 'IOTAUSDT']
  
  # Combinar todos los tiers en una lista plana
  all_symbols: [] # Se poblará automáticamente con tier_1 + tier_2 + tier_3
  
  timeframes: ['5m', '15m', '1h', '4h', '1d']
  start_date: '2022-01-01'
  lookback_periods: 200

# =============================================================================
# CONFIGURACIÓN ANTI-OVERFITTING
# =============================================================================
anti_overfitting:
  # Validación temporal estricta
  validation:
    method: "temporal_split"        # NUNCA usar random split
    train_ratio: 0.70              # 70% datos más antiguos
    val_ratio: 0.15                # 15% datos intermedios  
    test_ratio: 0.15               # 15% datos más recientes
    min_samples_per_split: 1000    # Mínimo samples por split
    
    # Walk-forward validation
    walk_forward:
      enabled: true
      initial_train_months: 6
      test_months: 1
      retrain_frequency_months: 1
      min_train_samples: 5000
  
  # Cross-validation temporal
  cross_validation:
    method: "TimeSeriesSplit"
    n_splits: 5
    test_size_months: 2
  
  # Thresholds para detección de overfitting
  detection_thresholds:
    max_train_val_accuracy_gap: 0.15    # 15% máximo gap
    max_train_val_loss_ratio: 2.0       # Loss ratio máximo
    min_acceptable_accuracy: 0.60       # 60% mínimo accuracy
    stability_threshold: 0.20           # 20% máximo coef. variación
    live_backtest_gap: 0.30             # 30% máximo gap live vs backtest
    
  # Auto-reentrenamiento
  auto_retrain:
    enabled: true
    trigger_conditions:
      - 'accuracy_below_threshold'
      - 'stability_degradation'
      - 'regime_change_detected'
    
    retrain_schedule:
      frequency: 'weekly'
      min_days_between: 3
      max_auto_retrains_per_week: 2

# =============================================================================
# MODELOS CON REGULARIZACIÓN AGRESIVA
# =============================================================================
models:
  # Detector de Momentum (≥5%)
  momentum:
    algorithm: "regularized_xgboost"
    params:
      n_estimators: 100
      max_depth: 4
      learning_rate: 0.03
      subsample: 0.7
      colsample_bytree: 0.7
      reg_alpha: 10
      reg_lambda: 10
      min_child_weight: 10
      gamma: 1
    
    early_stopping_rounds: 15         # Para después de 15 sin mejora
    feature_selection:
      method: 'SelectKBest'
      k: 50
      score_func: 'f_regression'
  
  # Clasificador de Regímenes
  regime:
    algorithm: "regularized_xgboost"  
    params:
      n_estimators: 100
      max_depth: 4
      learning_rate: 0.05
      subsample: 0.7
      colsample_bytree: 0.7
      reg_alpha: 10
      reg_lambda: 15
      min_child_weight: 10
      gamma: 1
    
    early_stopping_rounds: 20
    feature_selection:
      method: 'SelectKBest'
      k: 40
      score_func: 'f_regression'
  
  # Predictor de Rebotes (1-3%)
  rebound:
    algorithm: "regularized_lstm"
    params:
      sequence_length: 24
      lstm_units: 50
      dropout_rate: 0.5
      recurrent_dropout: 0.3
      batch_normalization: true
      l2_regularization: 0.01
    
    early_stopping:
      patience: 15
      monitor: 'val_loss'
      restore_best_weights: true
    
    callbacks:
      - 'EarlyStopping'
      - 'ReduceLROnPlateau'

# =============================================================================
# FEATURE ENGINEERING ANTI-OVERFITTING
# =============================================================================
features:
  # Normalización obligatoria
  normalization:
    enabled: true
    method: "standard_scaler"        # StandardScaler para consistency
    per_symbol: true                 # Normalizar por símbolo
  
  # Selección de features robustas
  selection:
    remove_regime_specific: true     # Quitar features específicos de régimen
    correlation_threshold: 0.95      # Quitar features correlacionadas >95%
    stability_window: 30             # Ventana para medir stability
    min_importance_threshold: 0.01   # Mínima importancia para incluir
  
  # Features técnicos robustos
  technical_indicators:
    # Momentum indicators (robustos a diferentes mercados)
    rsi_periods: [7, 14, 21]
    macd_config: [12, 26, 9]
    roc_periods: [5, 10, 20]
    
    # Volatility indicators
    atr_period: 14
    bollinger_bands: [20, 2]
    
    # Volume indicators  
    obv_enabled: true
    volume_sma_period: 20
    
    # Trend indicators
    adx_period: 14
    sma_periods: [5, 10, 20, 50]
    ema_periods: [12, 26, 50]

# =============================================================================
# MONITOREO Y ALERTAS
# =============================================================================
monitoring:
  # Logging detallado
  logging:
    level: "INFO"
    overfitting_alerts: true
    performance_tracking: true
    feature_drift_monitoring: true
  
  # Métricas de performance
  metrics:
    # Métricas principales
    primary: ["accuracy", "precision", "recall", "f1_score"]
    
    # Métricas específicas de trading
    trading_specific: ["directional_accuracy", "sharpe_ratio", "max_drawdown"]
    
    # Métricas de estabilidad
    stability: ["coefficient_variation", "regime_consistency"]
  
  # Reportes automáticos
  reporting:
    overfitting_report_frequency: "daily"
    performance_summary_frequency: "weekly"
    model_health_check_frequency: "daily"

# =============================================================================
# CONFIGURACIÓN DE ENTRENAMIENTO
# =============================================================================
training:
  # Recursos de hardware (optimizado para laptop)
  hardware:
    max_threads: 4                   # Máximo 4 threads para laptop
    max_processes: 2                 # Máximo 2 procesos
    memory_limit_gb: 8               # Límite de memoria
    batch_processing: true           # Procesar en lotes
  
  # Pipeline de entrenamiento
  pipeline:
    data_validation: true            # Validar datos antes de entrenar
    feature_engineering: true       # Calcular features automáticamente
    model_selection: true           # Seleccionar mejor modelo
    overfitting_detection: true     # Detectar overfitting automáticamente
    
  # Gestión de modelos
  model_management:
    save_best_only: true            # Solo guardar mejores modelos
    version_control: true           # Versionar modelos
    backup_frequency: "weekly"      # Backup semanal
    max_model_versions: 5           # Mantener últimas 5 versiones

# =============================================================================
# API Y EXTERNAL SERVICES
# =============================================================================
api:
  binance:
    rate_limit_per_minute: 1200     # Respetar límites Binance
    chunk_size_days: 30
    max_retries: 3
    retry_delay: 1
    backoff_factor: 2
    
    # Configuración para 30 símbolos
    concurrent_downloads: 5          # Máximo 5 descargas simultáneas
    symbols_per_batch: 10           # Procesar 10 símbolos por lote

# =============================================================================
# CONFIGURACIÓN DE PRODUCCIÓN
# =============================================================================
production:
  # Configuración para live trading (cuando esté listo)
  live_trading:
    enabled: false                   # Inicialmente disabled
    paper_trading_first: true       # Siempre probar en paper primero
    min_confidence_threshold: 0.75  # 75% mínimo confianza para signal
    max_position_size: 0.02         # 2% máximo por posición
    
  # Seguridad
  safety:
    max_daily_trades: 10            # Máximo 10 trades por día
    emergency_stop_loss: 0.05       # 5% stop loss de emergencia
    model_health_required: true     # Modelo debe estar saludable
